# Generated by Django 4.2.1 on 2025-06-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_order_delivered_order_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='kasserine', max_length=100),
            preserve_default=False,
        ),
    ]
